#!/bin/sh
cat <<_EOS-1

********************************************
Enigma2 PyShell plugin installed
********************************************

_EOS-1

cat /usr/lib/enigma2/python/Plugins/Extensions/PyShell/README.txt

cat <<_EOS-2

********************************************
Restart box to complete install
********************************************

_EOS-2

exit 0
