#!/bin/sh
cat <<_EOS-1

********************************************
Removing files
********************************************

_EOS-1

rm -r /usr/lib/enigma2/python/Plugins/Extensions/SnackBar > /dev/null 2>&1

cat <<_EOS-2

********************************************
Enigma2 SnackBar plugin uninstalled
********************************************

********************************************
Restart box to complete uninstall
********************************************

_EOS-2

exit 0
